<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7Ihx7fD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7Ihx7fD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7Ihx7fD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7Ihx7fD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container7Ihx7fD\App_KernelDevDebugContainer([
    'container.build_hash' => '7Ihx7fD',
    'container.build_id' => '217645b9',
    'container.build_time' => 1707577562,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'Container7Ihx7fD');
